#!/bin/bash -ex
# we should always set proper ownership before exiting, otherwise
# the created packages will have root:root ownership and we'll be unable
# to delete them from our host.
trap 'chown -R --reference /build-inside/build-package /out/' EXIT

virtualenv ${INSTALL_DIR}
${INSTALL_DIR}/bin/pip install /source
# it would be better to choose stable, exact versions.
source ${INSTALL_DIR}/bin/activate
cd ${INSTALL_DIR}
# create the ourcms user; it's easier to chown here rather than manually set the ownership later on.
/build-inside/before-install-and-upgrade

mkdir cms
mkdir -m 0750 state
pushd cms
djangocms --db sqlite://localhost//${INSTALL_DIR}/state/project.db --no-input -f -p . ourcms
popd

chown -R ourcms:nogroup state

pip install uwsgi
install -D /build-inside/upstart/ourcms.conf /etc/init/ourcms.conf

cd /out
# this is a standard fpm command. look at fpm's own help. The only thing that I like to do
# is installing all the things in a separate dir to prevent listing all the files - but it's
# just personal taste.
# remember to list all your runtime dependencies, e.g. the shared libraries you link to.
fpm -t deb -s dir -n ourcms --version ${VERSION} --description "my cms ${GIT_COMMIT}" --deb-use-file-permissions --deb-no-default-config-files --before-install /build-inside/before-install-and-upgrade --before-upgrade /build-inside/before-install-and-upgrade --before-remove /build-inside/before-remove --after-remove /build-inside/after-remove --after-upgrade /build-inside/after-upgrade --depends python --depends libpython2.7 --depends libjpeg8 --depends zlib1g --config-files /opt/ourcms/state -C / /opt /etc/init/ourcms.conf
